### ISSUE TITLE
Really supportive of this effort!

### ISSUE THREAD

**Issue by miketheitguy** [WICG/dbsc#22]
I'm not sure exactly how I'd be able to assist in such an endeavor, but I'd like to throw my hat in the ring for support. Session cookies are part of the "last mile" of authentication that has often gotten lost in the sauce in conversations around passkeys and stronger MFA mechanisms. Yet the techniques to get at session data aren't terribly more sophisticated than what we've already seen for decades (hey download this office document or totally trustworthy PDF shipping invoice with executable code).

**Comment by kmonsen** [comment]
Thank you!
