### ISSUE TITLE
Maintaining a session: essential optimization can be achieved 

### ISSUE THREAD

**Issue by alextok** [WICG/dbsc#3]
During maintaining the session we do two roundtrips, but we can do one.

In the current proposal, we are doing 

1. Request challenge - 1 network call
2. Sign challenge and send PoP request - the second call.

If we allow the web site append the challenge to its normal requests, and the browser to cache it, we will be able to save on the first call.  

Let's assume we have gmail that pulls emails and shows user presence icon:

Every time the web app pulls email, gmail service can add to any response an extra header:

Sec-Session-Challenge: new_challenge

The client will store this new_challenge and when it will call securesession/refresh, it can provide PoP with the freshest challenge, without doing an extra round trip.

GET /securesession/refresh
Sec-Session-Response: base64-URL-encoded-JWT-with-new_challenge

So, we are avoiding the network round trip, in favor adding new challenge to every or some server responses. Please, note usually the challenge generation is cheap, the biggest lost is the network roundtrip.

This challenge can be expired, securesession/refresh still can respond with better challenge, but in majority cases it will be one network roundtrip instead of two.

**Comment by kmonsen** [comment]
Yes, we have thought about this, I can put that header in. The server might also not need to have the challenge done every time it refreshes the cookies.

**Comment by alextok** [comment]
>The server might also not need to have the challenge done every time it refreshes the cookies.

that is not clear to me, how server will put in cookie thumbprint of the key, if it didn't check possession of the private key. I want to learn more about it.

**Comment by kmonsen** [comment]
I added a section about this optimization here: https://github.com/WICG/dbsc/commit/002a162af1dfe14c8f6143aa8043fc4b3172d8f3

If you were thinking of something else, please let me know or suggest a patch.

To answer your question, the server could asses the security of the session based on many parameters and decide at the moment it is safe enough to refresh cookies without checking possession of the private key.

**Comment by kmonsen** [comment]
Closing this issue, please reopen if your concern was not addressed.
