### ISSUE TITLE
Adjust explainer for web platform naming convention

### ISSUE THREAD

**Issue by jeremyroman** [WICG/dbsc#4]
See, for reference, https://w3ctag.github.io/design-principles/#naming-consistency.

For example:

1. WebIDL properties should be named in camel case, so probably `navigator.secureSession` rather than `navigator.securesession`
2. the dictionary passed to it should likely also follow this convention (WebIDL dictionary keys), except possibly if it is essentially JSON data
3. "alg" rather than "algorithm" may not have precedent on the web platform (WebCrypto seems to use the full word); if so the naming should probably be consistent with that unless there's reason to diverge

**Comment by kmonsen** [comment]
Thank you, I have tried to address all these.
