### ISSUE TITLE
What is the expectation of multi-site cross-site signatures?

### ISSUE THREAD

**Issue by wparad** [WICG/dbsc#40]
> Cross-site/cross-origin data leakage: It should be impossible for a site to use this API to circumvent the same origin policy, 3P cookie policies, etc. (More on this below.)

Often we generate a session on one subdomain and then it will get used/refreshed on another subdomain. Rarely, although this does happen it will be a completely separate eTLD. Third party cookies are basically dead, and we've all but given up on supporting cross-site session like this, but realistically this is a fundamental need we have and right now there doesn't seem to be any solution to this. 

At very least our requirement would be that the DBSC public key is consistent across an entire eTLD, and hopefully it would be consistent across the device in some non-linkable/non-trackable way, the proposal doesn't talk about that at all. It does reference that it will talk about this but then says **More on this below**, but I don't see where there is actually more.

**Comment by kmonsen** [comment]
Each DBSC session has a unique key, and it should not be possible to see if two different sessions are on the same device. There can be many sessions for an eTLD+1, for example for google.com we plan to use two different sessions.

This is a bit different on the enterprise version where the local key helper can generate keys in any way it wants.

One thing to understand here is that right now refresh and registration requests can be redirected by the server.
