### ISSUE TITLE
Can we clarify, if the challenges can be returned from negative responses as well.

### ISSUE THREAD

**Issue by alextok** [WICG/dbsc#6]
> The server can also serve challenges ahead of time attached to any response as an optimization ...

The example shows 200OK, but the question can negative response serve challenges?

IMHO, the challenge is not relevant to the particular request, and we can and should return challenges for negative responses, as well as all kind of redirect.

So, ANY HTTP status message can server the challenges.

**Comment by arnar** [comment]
Yes, challenges should be allowed on any response. I'll add a clarification, leaving this open as a reminder.

**Comment by kmonsen** [comment]
I think you mean the preemptive challenge? I reduced the example to make it more clear that challenges ahead of time can come on any request here: https://github.com/WICG/dbsc/commit/b0754c7443437605c86e727631ae9fe2300dfc8e

Let me know if this addresses your concern.

**Comment by alextok** [comment]
yes, this works. thanks.
