### ISSUE TITLE
Refresh session performance 1: Waiting for response from the server. 

### ISSUE THREAD

**Issue by alextok** [WICG/dbsc#60]
DBSC performs well during active use of the web app but struggles when the device or web app has been idle for a while.

If the device has been unused or a browser tab inactive, the auth cookies will expire. Before allowing workload requests, the cookie needs to be updated. This requires the client to wait for a network call to the session refresh endpoint before workload navigation can proceed. Therefore, there are two requests:

1. Session refresh request.
2. Wait for response.
3. Workload request.

We can address this problem by including a special header in the request with refresh session information. There could be alternative approaches.

Similar issue discussed here: https://github.com/WICG/dbsc/issues/12

**Comment by danmarg** [comment]
What do you mean by "a special header in the request?" In which request? 

Maybe easier to illustrate with an example. :)

**Comment by kmonsen** [comment]
This has been addressed in the explainer, there is a new mode where instead of deferring requests it will sign requests with the regular JWT until there is a valid session.
