### ISSUE TITLE
Is there a timeline for when DBSC will be available on OSX and other OSs?

### ISSUE THREAD

**Issue by ahallsc** [WICG/dbsc#64]
Based on the [testing early versions of DBSC page](https://github.com/WICG/dbsc/wiki/Testing-early-versions-of-DBSC) only windows devices are currently supported. Is there a timeline when this will expand to mac OS and other OSs?

Will the project be expanded to use the T2 chip instead of TPM on mac?

**Comment by kmonsen** [comment]
We are planning to do an origin trial in Q1 2025, and the goal is for Mac Secure Enclave to be supported by default.
