### ISSUE TITLE
navigator.secureSession is undefined on Chrome 132

### ISSUE THREAD

**Issue by CamiloGarciaLaRotta** [WICG/dbsc#82]
## What
👋🏼 currently in the process of writing a Gem to abstract most of the DBSC scaffolding for Rails web applications. I followed the wiki instructions and enabled these flags on Chrome 132 on a Win11 VM. However, on the dev tools console, `navigator` doesn't have a secure session attribute as mentioned in the readme. Are there any additional steps that the wiki may be missing?

![image](https://github.com/user-attachments/assets/0f95d0d6-7163-4d0b-bedc-5bb948e68d6d)

FWIW I am able to create sessions via the demo server: https://dbsc-prototype-server.glitch.me, which leads me to believe that the setup is correct and maybe the navigator API is just not available for public use yet?

**Comment by jcat4** [comment]
I tested on the latest Chrome Beta, version 132.0.6834.32, on a Windows 11 device natively (`Device Bound Session Credentials with software keys` not enabled cus I have TPM access). I am experiencing the same thing, `navigator.secureSession` is not defined

**Comment by drubery** [comment]
The phrase "Alternative JavaScript API" was supposed to indicate that it was possible future work. Sorry that was unclear, I've adjusted the phrasing. The JS API is not planned as part of the initial DBSC origin trial, so `navigator.secureSession` will not exist in the near future.
